---
- name: httpd install
  hosts: all
  become: yes

  tasks:
  - name: apache2
    apt:
      name: apache2
      state: present

  - name: starting httpd
    service:
      name: apache2
      state: started
      enabled: yes
