---
- name: downloadfiles
  hosts: all

  tasks:
  - name: download file to host
    get_url:
      url: https://www.python.org/ftp/python/3.12.3/python-3.12.3-amd64.exe
      dest: /tmp/
      owner: satya
      group: QA
      mode: 0777
