---
 - name: Nginx install and start
   hosts: all
   become: yes
   vars:
    - apps: [python3,vim,telnet]

   tasks:
   - name: Installing nginx
     apt:
       name: "{{ item }}"
       state: present
     tags: i-nginx
     with_items: "{{ apps }}"
   
