---
- name: Set password
  hosts: all
  become: yes

  tasks:
  - name: createpassword
    user: 
      name: Veera
      update_password: always
      password: "{{'Veera@9533' | password_hash('sha512')}}"
